const fs = require("fs/promises");
const path = require("path");
const { safeSpawn } = require("../lib/safeSpawn");
function safeDomain(domain) { const value = String(domain || "").toLowerCase(); if (!/^(?=.{1,253}$)([a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/.test(value)) { const e = new Error("Invalid domain"); e.code = "INVALID_DOMAIN"; throw e; } return value; }
function safePort(port) { const n = Number(port); if (!Number.isInteger(n) || n < 1 || n > 65535) throw new Error("Invalid upstream port"); return n; }
function safeUploadLimit(value) { const raw = String(value || "50m").trim(); if (!/^\d+[kKmMgG]?$/.test(raw)) throw new Error("Invalid upload limit"); return raw; }
function safeTimeout(value) { const n = Number(value || 60); if (!Number.isInteger(n) || n < 5 || n > 600) throw new Error("Invalid proxy timeout"); return n; }
function nginxConfig(payload) { const domain = safeDomain(payload.domain); const port = safePort(payload.upstreamPort); const uploadLimit = safeUploadLimit(payload.uploadLimit); const timeout = safeTimeout(payload.proxyTimeout); return `server {\n  listen 80;\n  server_name ${domain};\n  client_max_body_size ${uploadLimit};\n  access_log /var/log/nginx/${domain}.access.log;\n  error_log /var/log/nginx/${domain}.error.log;\n\n  location / {\n    proxy_pass http://127.0.0.1:${port};\n    proxy_http_version 1.1;\n    proxy_set_header Host $host;\n    proxy_set_header X-Real-IP $remote_addr;\n    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n    proxy_set_header X-Forwarded-Proto $scheme;\n    ${payload.websocket ? "proxy_set_header Upgrade $http_upgrade;\n    proxy_set_header Connection \"upgrade\";" : ""}\n    proxy_read_timeout ${timeout}s;\n  }\n}\n`; }
function apacheConfig(payload) { const domain = safeDomain(payload.domain); const port = safePort(payload.upstreamPort); return `<VirtualHost *:80>\n  ServerName ${domain}\n  ProxyPreserveHost On\n  ProxyPass / http://127.0.0.1:${port}/\n  ProxyPassReverse / http://127.0.0.1:${port}/\n  ErrorLog /var/log/apache2/${domain}.error.log\n  CustomLog /var/log/apache2/${domain}.access.log combined\n</VirtualHost>\n`; }
async function writeNginxSite(payload) { const domain = safeDomain(payload.domain); const file = `/etc/nginx/sites-available/${domain}.conf`; await fs.writeFile(file, nginxConfig(payload), { mode: 0o644 }); const enabled = `/etc/nginx/sites-enabled/${domain}.conf`; await fs.symlink(file, enabled).catch(() => null); return { file, enabled }; }
async function writeApacheSite(payload) { const domain = safeDomain(payload.domain); const file = `/etc/apache2/sites-available/${domain}.conf`; await fs.writeFile(file, apacheConfig(payload), { mode: 0o644 }); return { file }; }
async function test(payload) { const server = payload.server === "apache" ? "apache" : "nginx"; return server === "apache" ? safeSpawn("apachectl", ["configtest"], { timeout: 15000 }) : safeSpawn("nginx", ["-t"], { timeout: 15000 }); }
module.exports = { writeNginxSite, writeApacheSite, test, nginxConfig, apacheConfig };
