const router = require("express").Router();
const { z } = require("zod");
const { prisma } = require("../../config/prisma");
const { requireAuth } = require("../../middleware/auth");
const { requirePermission } = require("../../middleware/rbac");
const { validate } = require("../../middleware/validate");
const { audit } = require("../../middleware/audit");
const { asyncHandler } = require("../../utils/asyncHandler");
const { ok, fail } = require("../../utils/response");
const { callAgent } = require("../../services/agentClient");
const engines = { postgresql: 5432, mysql: 3306, mariadb: 3306, mongodb: 27017, redis: 6379, sqlite: 0 };
const serverDto = z.object({ name: z.string().min(2).max(80), engine: z.enum(Object.keys(engines)), host: z.string().max(120).default("localhost"), port: z.number().int().min(0).max(65535), accessMode: z.enum(["localhost_only", "allowlist", "public"]).default("localhost_only"), username: z.string().max(80).optional() });
const databaseDto = z.object({ name: z.string().min(1).max(80).regex(/^[a-zA-Z0-9_-]+$/), owner: z.string().max(80).optional() });
router.use(requireAuth);
router.get("/engines", requirePermission("databases.manage"), asyncHandler(async (req, res) => ok(res, "Database engines", { engines: Object.entries(engines).map(([id, port]) => ({ id, port, remoteAccessWarning: port !== 0 })) })));
router.get("/", requirePermission("databases.manage"), asyncHandler(async (req, res) => { const servers = await prisma.databaseServer.findMany({ include: { databases: true, users: true }, orderBy: { createdAt: "desc" } }); return ok(res, "Database servers", { servers }); }));
router.post("/", requirePermission("databases.manage"), validate(serverDto), audit("database_server_created", "database_server"), asyncHandler(async (req, res) => { if (req.body.accessMode === "public" && [5432,3306,6379,27017].includes(req.body.port)) return fail(res, 409, "Public database access is blocked. Use localhost-only or an IP allowlist.", "DATABASE_PUBLIC_ACCESS_BLOCKED"); const server = await prisma.databaseServer.create({ data: req.body }); return ok(res, "Database server created", { server }); }));
router.post("/:id/databases", requirePermission("databases.manage"), validate(databaseDto), asyncHandler(async (req, res) => { const db = await prisma.managedDatabase.create({ data: { serverId: req.params.id, name: req.body.name, owner: req.body.owner } }); await prisma.auditLog.create({ data: { userId: req.user.id, action: "database_created", resource: "database", resourceId: db.id, metadata: { name: db.name } } }); return ok(res, "Database registered", { database: db }); }));
router.post("/:id/status", requirePermission("databases.manage"), asyncHandler(async (req, res) => { const server = await prisma.databaseServer.findUnique({ where: { id: req.params.id } }); if (!server) return fail(res, 404, "Database server not found", "DATABASE_SERVER_NOT_FOUND"); const serviceName = server.engine === "postgresql" ? "postgresql" : server.engine; const data = await callAgent("service.status", { service: serviceName }).catch((error) => ({ status: "unknown", warning: error.message })); return ok(res, "Database service status", { server, status: data }); }));
module.exports = router;
